import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Star, Clock, Users, X } from "lucide-react";
import CourseInstructor from "../Courseinstructor/CourseInstructor";
import CoursePlan from "../CoursePlan/CoursePlan";
import CourseDetails from "../CourseDetails/CourseDetails";
import CourseFeatures from "../CourseFeature/CourseFeature";
const CourseBanner = ({ title = "Advanced Machine Learning and AI", instructor = "Dr. Jane Smith", rating = 4.8, studentsEnrolled = 15000, duration = "10 weeks", level = "Advanced", category = "Computer Science", backgroundImage = "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80", }) => {
    const [isModalOpen, setModalOpen] = useState(false);
    const [selectedTab, setSelectedTab] = useState("instructor");
    const openModal = () => setModalOpen(true);
    const closeModal = () => setModalOpen(false);
    return (_jsxs("div", { className: "container mx-auto my-8", children: [_jsx(Button, { onClick: openModal, className: "bg-blue-600 text-white mb-4", children: "Open Course View" }), isModalOpen && (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50 ", children: _jsxs("div", { className: "relative w-full max-w-4xl mx-auto bg-white rounded-lg overflow-hidden", children: [_jsx("button", { onClick: closeModal, className: "absolute top-4 right-4 bg-gray-200 rounded-full p-2", "aria-label": "Close modal", children: _jsx(X, { className: "w-5 h-5 text-gray-600" }) }), _jsxs("div", { className: "relative mt-20 w-full h-[260px] bg-cover bg-center text-white", style: { backgroundImage: `url(${backgroundImage})` }, children: [_jsx("div", { className: "absolute inset-0 bg-black opacity-60" }), _jsx("div", { className: "relative z-10 h-full max-w-6xl mx-auto px-4 py-16 sm:px-6 lg:px-8 flex flex-col justify-center", children: _jsxs("div", { className: "space-y-6 text-start", children: [_jsx("h1", { className: "text-4xl font-bold tracking-tight sm:text-5xl", children: title }), _jsxs("p", { className: "text-xl", children: ["Taught by ", _jsx("span", { className: "font-semibold", children: instructor })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(Star, { className: "w-5 h-5 text-yellow-400" }), _jsx("span", { className: "ml-1 font-medium", children: rating })] }), _jsxs("div", { className: "flex items-center", children: [_jsx(Users, { className: "w-5 h-5" }), _jsxs("span", { className: "ml-1", children: [studentsEnrolled.toLocaleString(), " students"] })] })] }), _jsxs("div", { className: "flex flex-wrap gap-4", children: [_jsxs(Badge, { className: "text-sm py-1 px-2 bg-white/20 text-white flex items-center", children: [_jsx(Clock, { className: "w-4 h-4 mr-1" }), duration] }), _jsx(Badge, { className: "text-sm py-1 px-2 bg-white/20 text-white", children: level }), _jsx(Badge, { className: "text-sm py-1 px-2 bg-white/20 text-white", children: category })] })] }) })] }), _jsxs("div", { className: "p-2", children: [_jsx("div", { className: "flex justify-center mb-4", children: _jsx("div", { className: "flex space-x-4 bg-gray-200 p-1 rounded-md shadow", children: ["instructor", "structure", "details", "feature"].map((tab) => (_jsx("button", { onClick: () => setSelectedTab(tab), "aria-selected": selectedTab === tab, className: `px-2 py-1 rounded-md transition-all duration-300 ${selectedTab === tab ? "bg-primary-default text-white" : "bg-gray-200 hover:bg-gray-300"}`, children: tab.charAt(0).toUpperCase() + tab.slice(1) }, tab))) }) }), _jsxs("div", { children: [selectedTab === "instructor" && _jsx(CourseInstructor, {}), selectedTab === "structure" && _jsx(CoursePlan, {}), selectedTab === "details" && _jsx(CourseDetails, {}), selectedTab === "feature" && _jsx(CourseFeatures, {})] })] })] }) }))] }));
};
export default CourseBanner;
