import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
const Career = () => {
    return (_jsxs("div", { className: "min-h-screen ", children: [_jsxs("section", { className: "mb-12", children: [_jsx("h2", { className: "text-4xl font-semibold mb-8 text-center text-gray-800", children: "Current Openings" }), _jsxs("div", { className: "grid gap-8 md:grid-cols-2 lg:grid-cols-3", children: [_jsxs("div", { className: "p-6 border border-gray-300 rounded-lg shadow-lg bg-white hover:shadow-xl transition", children: [_jsx("img", { src: "/path/to/frontend-dev.jpg" // Replace with an image related to the job
                                        , alt: "Frontend Developer", className: "w-full h-40 object-cover rounded-t-lg mb-4" }), _jsx("h3", { className: "text-2xl font-semibold mb-2 text-gray-800", children: "Frontend Developer" }), _jsx("p", { className: "text-gray-600 mb-4", children: "We are looking for a skilled Frontend Developer with experience in React and TypeScript to join our team." }), _jsx(Link, { to: "/careers/frontend-developer", className: "inline-block bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition", children: "View Details" })] }), _jsxs("div", { className: "p-6 border border-gray-300 rounded-lg shadow-lg bg-white hover:shadow-xl transition", children: [_jsx("img", { src: "/path/to/backend-dev.jpg" // Replace with an image related to the job
                                        , alt: "Backend Developer", className: "w-full h-40 object-cover rounded-t-lg mb-4" }), _jsx("h3", { className: "text-2xl font-semibold mb-2 text-gray-800", children: "Backend Developer" }), _jsx("p", { className: "text-gray-600 mb-4", children: "Seeking an experienced Backend Developer proficient in Node.js and MongoDB." }), _jsx(Link, { to: "/careers/backend-developer", className: "inline-block bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition", children: "View Details" })] }), _jsxs("div", { className: "p-6 border border-gray-300 rounded-lg shadow-lg bg-white hover:shadow-xl transition", children: [_jsx("img", { src: "/path/to/backend-dev.jpg" // Replace with an image related to the job
                                        , alt: "Backend Developer", className: "w-full h-40 object-cover rounded-t-lg mb-4" }), _jsx("h3", { className: "text-2xl font-semibold mb-2 text-gray-800", children: "Backend Developer" }), _jsx("p", { className: "text-gray-600 mb-4", children: "Seeking an experienced Backend Developer proficient in Node.js and MongoDB." }), _jsx(Link, { to: "/careers/backend-developer", className: "inline-block bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition", children: "View Details" })] }), _jsxs("div", { className: "p-6 border border-gray-300 rounded-lg shadow-lg bg-white hover:shadow-xl transition", children: [_jsx("img", { src: "/path/to/backend-dev.jpg" // Replace with an image related to the job
                                        , alt: "Backend Developer", className: "w-full h-40 object-cover rounded-t-lg mb-4" }), _jsx("h3", { className: "text-2xl font-semibold mb-2 text-gray-800", children: "Backend Developer" }), _jsx("p", { className: "text-gray-600 mb-4", children: "Seeking an experienced Backend Developer proficient in Node.js and MongoDB." }), _jsx(Link, { to: "/careers/backend-developer", className: "inline-block bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition", children: "View Details" })] })] })] }), _jsxs("section", { className: "bg-blue-50 p-8 rounded-lg text-center", children: [_jsx("h2", { className: "text-4xl font-bold mb-4 text-blue-900", children: "Why Work with Us?" }), _jsx("p", { className: "text-gray-700 mb-6", children: "We offer a collaborative work environment, competitive salaries, and growth opportunities. Join us and be part of a company that values innovation and creativity." }), _jsx(Link, { to: "/contact-us", className: "bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition", children: "Contact Us for Career Opportunities" })] })] }));
};
export default Career;
